listen_addresses = '*'
port = 5432
password_encryption = 'scram-sha-256'
logging_collector = on
log_destination = 'stderr'
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d.log'
log_rotation_age = '1d'
log_rotation_size = '10MB'
log_truncate_on_rotation = on
